logging:
  level:
    root: WARN

server:
  servlet:
    session:
      cookie:
        name: _ssid

spring:

  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost/databaseName
    username: username
    password: password

  main:
    banner-mode: 'OFF'

vimboard:
  www: /var/www/vimboard/public
