logging:
  level:
    root: WARN

server:
  servlet:
    session:
      cookie:
        name: session

spring:

  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost/databaseName
    username: username
    password: password

  freemarker:
    suffix: .ftlh

  main:
    banner-mode: 'OFF'
