# ============================================================================
# Vimboard default configuration file
# ----------------------------------------------------------------------------
#
# WARNING: Please leave this file unchanged. If you would like to make
# instance-specific changes to your own setup, please use application.yml.
#
# This is the default configuration. You can copy values from here and use them
# in your application.yml.
#


# ============================================================================
# SERVER SETTINGS
# ----------------------------------------------------------------------------

# Logging.
logging:
  level:
    root: INFO

# Server port.
server:
  address: localhost
  port: 8080

# Database connection.
spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost/databaseName
    username: username
    password: password


# ============================================================================
# VIMBOARD
# ----------------------------------------------------------------------------
vimboard:

  # Static content location
  www: /var/www/vimboard/public/


  # ==========================================================================
  # The common configuration for all boards.
  # --------------------------------------------------------------------------
  all:

    # ------------------------------------------------------------------------
    # General/misc settings
    # ------------------------------------------------------------------------

    # Shows some extra information at the bottom of pages. Good for
    # development/debugging.
    debug: false

    # The HTTP status code to use when redirecting. Can be either 303
    # "See Other" or 302 "Found". (303 is more correct but both should work.)
    # There is really no reason for you to ever need to change this.
    # http://www.w3.org/Protocols/rfc2616/rfc2616-sec10.html
    redirect-http: 303

    # ------------------------------------------------------------------------
    # Database settings
    # ------------------------------------------------------------------------

    # ------------------------------------------------------------------------
    # Cache, lock and queue settings
    # ------------------------------------------------------------------------

    # ------------------------------------------------------------------------
    # Cookie settings
    # ------------------------------------------------------------------------

    cookies:

      # Make this something long and random for security.
      salt: abcdefghijklmnopqrstuvwxyz09123456789!@#$%^&*()

    # ------------------------------------------------------------------------
    # Flood/spam settings
    # ------------------------------------------------------------------------

    # Enable reCaptcha to make spam even harder. Rarely necessary.
    recaptcha: false

    # ------------------------------------------------------------------------
    # Post settings
    # ------------------------------------------------------------------------

    # Load all country flags from one file.
    country-flags-condensed: true

    # Country flags stylesheet.
    country-flags-condensed-css: static/flags/flags.css

    # ------------------------------------------------------------------------
    # Ban settings
    # ------------------------------------------------------------------------

    # Allow users to appeal bans through Vimboard.
    ban-appeals: false

    # ------------------------------------------------------------------------
    # Markup settings
    # ------------------------------------------------------------------------

    # ------------------------------------------------------------------------
    # Image settings
    # ------------------------------------------------------------------------

    # ------------------------------------------------------------------------
    # Board settings
    # ------------------------------------------------------------------------

    # How to display the URI of boards. Usually "/{uri}/" (/b/, /mu/, etc).
    # This doesn't change the URL. Find {@link #boardPath} if you wish to
    # change the URL.
    board-abbreviation: "/{uri}/"

    # Allow unfiltered HTML in board subtitle.
    # This is useful for placing icons and links.
    allowSubtitleHtml: false

    # ------------------------------------------------------------------------
    # Display settings
    # ------------------------------------------------------------------------

    # The format string passed to string built-in for displaying dates.
    # https://freemarker.apache.org/docs/ref_builtins_date.html
    post-date: "MM/dd/yy (EEE) HH:mm:ss"

    # Custom stylesheets available for the user to choose.
    # See the "stylesheets/" folder for a list of available
    # stylesheets (or create your own).
    #
    stylesheets:
      Yotsuba B: '' # Default; there is no additional/custom stylesheet for this.
      Yotsuba: yotsuba.css
#     Futaba: futaba.css
#     Dark: dark.css

    # The prefix for each stylesheet URI. Defaults to {@link #root}/stylesheets/
#   uri-stylesheets: http://static.example.org/stylesheets/

    # The default stylesheet to use.
    default-stylesheet: Yotsuba B

    # Use Font-Awesome for displaying lock and pin icons, instead
    # of the images in static/.
    #
    # http://fortawesome.github.io/Font-Awesome/icon/pushpin/
    # http://fortawesome.github.io/Font-Awesome/icon/lock/
    font-awesome: true

    # Font-Awesome stylesheet.
    font-awesome-css: stylesheets/font-awesome/css/font-awesome.min.css

    # For lack of a better name, “boardlinks” are those sets of navigational
    # links that appear at the top and bottom of board pages. They can be a
    # list of links to boards and/or other pages such as status blogs and
    # social network profiles/pages.
    #
    # "Groups" in the boardlinks are marked with square brackets. Vimboard
    # allows for infinite recursion with groups. Each array in {@link #boards}
    # represents a new square bracket group.
    #
#   boards:
#     - General group:
#       - a
#       - b
#     - Second group:
#       - c
#       - d
#       - e: http://example.org/e
#     - f
#     - g
#     - Recursive:
#       - h
#       - Inner:
#         - i
#         - j
#     - status: http://example.org/status

    # Whether or not to put brackets around the whole board list.
    boardlist-wrap-bracket: false

    # ------------------------------------------------------------------------
    # Javascript
    # ------------------------------------------------------------------------

    # Additional Javascript files to include on board index and thread pages.
    # See "js/" for available scripts.
    additional-javascript:
      - js/jquery.min.js
      - js/inline-expanding.js
#     - js/local-time.js
    # Some scripts require jQuery. Check the comments in script files to see
    # what's needed. When enabling jQuery, you should first empty the array so
    # that "js/query.min.js" can be the first, and then re-add
    # "js/inline-expanding.js" or else the inline-expanding script might not
    # interact properly with other scripts.
    #  additional_javascript:
    #    - js/jquery.min.js
    #    - js/inline-expanding.js
    #    - js/auto-reload.js
    #    - js/post-hover.js
    #    - js/style-select.js
    #    - js/captcha.js

    # Where these script files are located on the web. Defaults to {@link #root}.
#   additional-javascript-url: http://static.example.org/tinyboard-javascript-stuff/

    # Compile all additional scripts into one file ({@link #fileScript})
    # instead of including them seperately.
    additional-javascript-compile: false

    # ------------------------------------------------------------------------
    # Video embedding
    # ------------------------------------------------------------------------

    # ------------------------------------------------------------------------
    # Error messages
    # ------------------------------------------------------------------------

    # ------------------------------------------------------------------------
    # Directory/file settings
    # ------------------------------------------------------------------------

    # The root directory, including the trailing slash,
    # Examples: '/', 'http://boards.chan.org/', '/chan/'.
    root: /

    # Name of the index page file.
    file-index: index.html

    # Name of the main script file.
    file-script: main.js

    # Board directory, followed by a forward-slash (/).
    board-path: "{uri}/"

    # Set custom location for stylesheets file. This can be used for load
    # balancing across multiple servers or hostnames.
#   url-stylesheet: http://static.example.org/style.css # main/base stylesheet

    # Set custom location for the main script file. This can be used for load
    # balancing across multiple servers or hostnames.
#   url-javascript: http://static.example.org/main.js

    # Website favicon.
#   url-favicon: /favicon.gif

    # ------------------------------------------------------------------------
    # Advanced build
    # ------------------------------------------------------------------------

    # ------------------------------------------------------------------------
    # Mod settings
    # ------------------------------------------------------------------------

    mod:

      # ----------------------------------------------------------------------
      # Mod settings
      # ----------------------------------------------------------------------

      # Number of entries to summarize and display on the dashboard.
      noticeboard-dashboard: 5

      # ----------------------------------------------------------------------
      # Mod permissions
      # ----------------------------------------------------------------------

      ## Post Controls

      # View IP addresses.
      show-ip: MOD

      ## Administration

      # View the report queue.
      reports: JANITOR

      # View list of bans.
      view-banlist: MOD

      # View IP address notes.
      view-notes: JANITOR

      # Create a new board.
      newboard: ADMIN

      # Manage existing boards (change title, etc).
      manageboards: ADMIN

      # List/manage users.
      manageusers: MOD

      # Promote/demote users.
      promoteusers: ADMIN

      # Edit any users' login information.
      editusers: ADMIN

      # Change user's own password.
      change-password: JANITOR

      # Create a user.
      createusers: ADMIN

      # View the moderation log.
      modlog: ADMIN

      # Create a PM (viewing mod usernames).
      create-pm: JANITOR

      # Search through posts, IP address notes and bans.
      search: JANITOR

      # Read the moderator noticeboard.
      noticeboard: JANITOR

      # Manage and install themes for homepage.
      themes: ADMIN

      # Execute un-filtered SQL queries on the database (?/debug/sql).
      debug-sql: DISABLED

      # Edit the current configuration (via web interface).
      edit-config: ADMIN

      # View ban appeals.
      view-ban-appeals: MOD

      # View the recent posts page.
      recent: MOD

      # Create pages.
      edit-pages: MOD

      # ------------------------------------------------------------------------
      # Other/uncategorized
      # ------------------------------------------------------------------------

      # Add links to dashboard (will all be in a new "Other" category).
#     dashboard-links:
#       Something: ?/something

    # ------------------------------------------------------------------------
    # Mod permissions
    # ------------------------------------------------------------------------

    # ------------------------------------------------------------------------
    # Public pages
    # ------------------------------------------------------------------------

    # ------------------------------------------------------------------------
    # Events (PHP 5.3.0+)
    # ------------------------------------------------------------------------

    # ------------------------------------------------------------------------
    # API settings
    # ------------------------------------------------------------------------

    # ------------------------------------------------------------------------
    # NNTPChan settings
    # ------------------------------------------------------------------------

    # ------------------------------------------------------------------------
    # Other/uncategorized
    # ------------------------------------------------------------------------

    # Meta keywords. It's probably best to include these in
    # per-board configurations.
#   meta-keywords: 'chan,anonymous discussion,imageboard,tinyboard'

    # Regex for board URIs. Don't add "`" character or any Unicode that MySQL
    # can't handle. 58 characters is the absolute maximum, because MySQL cannot
    # handle table names greater than 64 characters.
    board-regex: "[0-9a-zA-Z$_\u0080-\uFFFF]{1,58}"


  # ==========================================================================
  # Separate configurations that overrides settings
  # of the common configuration for each board.
  # --------------------------------------------------------------------------
# custom:


    # ========================================================================
    # /a/ board settings
    # ------------------------------------------------------------------------
#   a: ... same as allBoards ...


    # ========================================================================
    # /b/ board settings
    # ------------------------------------------------------------------------
#   b: ... same as allBoards ...
