# ------------------------------------------------------------------------------
# Vimboard default configuration file
# ------------------------------------------------------------------------------
#
# WARNING: Please leave this file unchanged. If you would like to make
# instance-specific changes to your own setup, please use application.yml.
#
# This is the default configuration. You can copy values from here and use them
# in your application.yml.
#


# ------------------------------------------------------------------------------
# LOGGING
# ------------------------------------------------------------------------------
logging:
  level:
    root: WARN


# ------------------------------------------------------------------------------
# DATABASE CONNECTION
# ------------------------------------------------------------------------------
spring:
#
# Database connection
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost/databaseName
    username: username
    password: password


# ------------------------------------------------------------------------------
# VIMBOARD
# ------------------------------------------------------------------------------
vimboard:
#
# Static content location
  www: /var/www/vimboard/public
