logging:
  level:
    root: FATAL

spring:

  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://192.168.56.101/vimboard
    username: vimadmin
    password: vimadmin123

  main:
    banner-mode: 'OFF'
